SistemaCadastroFornecedores/Models/ErrorViewModel.cs
namespace SistemaCadastroFornecedores.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SistemaCadastroFornecedores/Models/Fornecedor.cs
using System.ComponentModel.DataAnnotations;

public class FornecedoresModel
{
    public int ID { get; set; }

    [StringLength(100)]
    public string Nome { get; set; }



    [RegularExpression("^[0-9]*$", ErrorMessage = "CNPJ deve conter apenas dígitos.")]
    [StringLength(14)]
    public string CNPJ { get; set; }

    public string Especialidade { get; set; }

    [RegularExpression("^[0-9]*$", ErrorMessage = "CEP deve conter apenas dígitos.")]
    [StringLength(8)]
    public string CEP { get; set; }

    [StringLength(255)]
    public string Endereco { get; set; }
}

SistemaCadastroFornecedores/Models/FornecedorModel.cs
using System.ComponentModel.DataAnnotations;

public class FornecedorModel
{
    public int ID { get; set; }

    [StringLength(100)]
    public string Nome { get; set; }



    [RegularExpression("^[0-9]*$", ErrorMessage = "CNPJ deve conter apenas dígitos.")]
    [StringLength(14)]
    public string CNPJ { get; set; }

    public string Especialidade { get; set; }

    [RegularExpression("^[0-9]*$", ErrorMessage = "CEP deve conter apenas dígitos.")]
    [StringLength(8)]
    public string CEP { get; set; }

    [StringLength(255)]
    public string Endereco { get; set; }

    public  FornecedorModel(int id, string nome, string cnpj, string especialidade, string cep, string endereco)
    {
        ID = id;
        Nome = nome;
        CNPJ = cnpj;
        Especialidade = especialidade;
        CEP = cep;
        Endereco = endereco;

    }
}

SistemaCadastroFornecedores/Controllers/FornecedorController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaCadastroFornecedores.Controllers
{
    public class FornecedorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar()
        {
            return View();
        }

        public IActionResult ApagarConfirmacao()
        {
            return View();
        }
    }
}

SistemaCadastroFornecedores/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaCadastroFornecedores.Models;
using System.Diagnostics;

namespace SistemaCadastroFornecedores.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaCadastroFornecedores/Views/Fornecedor/ApagarConfirmacao.cshtml
@model List<FornecedorModel>

@{
    ViewData["Title"] = "Listagem de Fornecedores";
}

<div class="text-center">
    <h3>Realmente deseja excluir o fornecedor?</h3>
</div>

<a class="btn btn-primary" role="button" asp-controller="Fornecedor" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger" role="button" asp-controller="Fornecedor" asp-action="Apagar">Confirmar exclusão</a>

SistemaCadastroFornecedores/Views/Fornecedor/Criar.cshtml
@model List<FornecedorModel>

@{
    ViewData["Title"] = "Listagem de Fornecedores";
}

<div class="text-center">
    <br />
    <h1 class="display-4">Cadastrar Fornecedor</h1>
</div>

<form>
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" class="form-control" placeholder="Digite seu nome">
    </div>

    <div class="form-group">
        <label for="CNPJ">CNPJ</label>
        <input type="text" class="form-control" id="cnpj" placeholder="Digite seu CNPJ" maxlength="14" oninput="this.value = this.value.replace(/[^0-9]/g, '');">
    </div>

    <div class="form-group">
        <label for="especialidade">Especialidade</label>
        <select class="form-control" id="especialidade">
            <option value="comercio">Comércio</option>
            <option value="servico">Serviço</option>
            <option value="industria">Indústria</option>
        </select>
    </div>

    <div class="form-group">
        <label for="CEP">CEP</label>
        <input type="text" class="form-control" id="cep" placeholder="Digite seu CEP" maxlength="8" oninput="this.value = this.value.replace(/[^0-9]/g, '');">
    </div>

    <div class="form-group">
        <label for="endereco">Endereço</label>
        <input type="text" class="form-control" id="endereco" placeholder="Endereço" maxlength="255" disabled>
    </div>

    <script>
        const cepInput = document.getElementById('cep');
        const enderecoInput = document.getElementById('endereco');

        cepInput.addEventListener('blur', async () => {
            const cep = cepInput.value.replace(/[^0-9]/g, '');

            if (cep.length === 8) {
                const response = await fetch(`https://viacep.com.br/ws/${cep}/json/`);
                const data = await response.json();

                if (!data.erro) {
                    enderecoInput.value = data.logradouro + ', ' + data.bairro + ', ' + data.localidade + '/' + data.uf;
                }
            }
        });
    </script>

    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="Fornecedor" asp-action="Index" role="button">Voltar</a>
</form>

SistemaCadastroFornecedores/Views/Fornecedor/Editar.cshtml
@model List<FornecedorModel>

@{
    ViewData["Title"] = "Listagem de Fornecedores";
}

<div class="text-center">
    <br />
    <h1 class="display-4">Editar Fornecedor</h1>
</div>

<form>
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" class="form-control" placeholder="Digite seu nome">
    </div>

    <div class="form-group">
        <label for="CNPJ">CNPJ</label>
        <input type="text" class="form-control" id="cnpj" placeholder="Digite seu CNPJ" maxlength="14" oninput="this.value = this.value.replace(/[^0-9]/g, '');">
    </div>

    <div class="form-group">
        <label for="especialidade">Especialidade</label>
        <select class="form-control" id="especialidade">
            <option value="comercio">Comércio</option>
            <option value="servico">Serviço</option>
            <option value="industria">Indústria</option>
        </select>
    </div>

    <div class="form-group">
        <label for="CEP">CEP</label>
        <input type="text" class="form-control" id="cep" placeholder="Digite seu CEP" maxlength="8" oninput="this.value = this.value.replace(/[^0-9]/g, '');">
    </div>

    <div class="form-group">
        <label for="endereco">Endereço</label>
        <input type="text" class="form-control" id="endereco" placeholder="Endereço" maxlength="255" disabled>
    </div>

    <script>
        const cepInput = document.getElementById('cep');
        const enderecoInput = document.getElementById('endereco');

        cepInput.addEventListener('blur', async () => {
            const cep = cepInput.value.replace(/[^0-9]/g, '');

            if (cep.length === 8) {
                const response = await fetch(`https://viacep.com.br/ws/${cep}/json/`);
                const data = await response.json();

                if (!data.erro) {
                    enderecoInput.value = data.logradouro + ', ' + data.bairro + ', ' + data.localidade + '/' + data.uf;
                }
            }
        });
    </script>

    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Fornecedor" asp-action="Index" role="button">Voltar</a>
</form>

SistemaCadastroFornecedores/Views/Fornecedor/Index.cshtml
@model List<FornecedorModel>

@{
    ViewData["Title"] = "Listagem de Fornecedores";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Fornecedor" asp-action="Criar" >Adicionar novo fornecedor</a>
    </div>
    <br />
    <h1 class="display-4">Listagem de Fornecedores</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nome</th>
                <th scope="col">CNPJ</th>
                <th scope="col">Especialidade</th>
                <th scope="col">CEP</th>
                <th scope="col">Endereco</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Ayumi</td>
                <td>04.153.860/0001-16</td>
                <td>Têxtil</td>
                <td>03677060</td>
                <td>Zona Leste favelona</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button" class="btn btn-primary" asp-controller="Fornecedor" asp-action="Editar">Editar</a>
                        <a role="button" class="btn btn-danger" asp-controller="Fornecedor" asp-action="ApagarConfirmacao">Apagar</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Jacob</td>
                <td>Thornton</td>
                <td>fat</td>
                <td>fat</td>
                <td>fat</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button" class="btn btn-primary" asp-controller="Fornecedor" asp-action="Editar">Editar</a>
                        <a role="button" class="btn btn-danger" asp-controller="Fornecedor" asp-action="ApagarConfirmacao">Apagar</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td>Larry the Bird</td>
                <td>twitter</td>
                <td>twitter</td>
                <td>twitter</td>
                <td>twitter</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button" class="btn btn-primary" asp-controller="Fornecedor" asp-action="Editar">Editar</a>
                        <a role="button" class="btn btn-danger" asp-controller="Fornecedor" asp-action="ApagarConfirmacao">Apagar</a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>

SistemaCadastroFornecedores/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo</h1>
    <p>Sistema de cadastro de Fornecedores</p>
</div>

SistemaCadastroFornecedores/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadastro de Fornecedores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaCadastroFornecedores.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cadastro de Fornecedores</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cadadastro de Fornecedores
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>